import "./globals.css";
import "./burger.css";
import { Footer } from "./components/Footer/Footer";
import { Navbar } from "./components/Navbar/Navbar";

export const metadata = {
  title: "Adam Reich",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="scrollbar-thin scrollbar-track-[#181818] scrollbar-thumb-[#00AEEF]"
      suppressHydrationWarning
    >
      <head>
        <script
          src="https://static.elfsight.com/platform/platform.js"
          data-use-service-core
          defer
        ></script>
        <script async src="https://link.msgsndr.com/js/form_embed.js"></script>
      </head>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
